#pragma once

#define MACHINE_MEMORY_SIZE 4096
#define PIXEL_SIZE 20
#define MACHINE_WIDTH 64
#define MACHINE_HEIGHT 32
#define WINDOW_WIDTH MACHINE_WIDTH * PIXEL_SIZE
#define WINDOW_HEIGHT MACHINE_HEIGHT * PIXEL_SIZE
#define NUM_V_REGS 16
#define STACK_SIZE 16
#define NUMBER_OF_KEYS 16
#define PROGRAM_START 0x200

#define FPS 10
#define FRAME_TARGET_TIME (1000 / FPS)